// Generated by CoffeeScript 1.6.1
(function() {
  var Test,
    _this = this;

  Test = (function() {

    function Test(singool) {
      var _this = this;
      this.singool = singool;
      this.run = function() {
        return Test.prototype.run.apply(_this, arguments);
      };
    }

    Test.prototype.description = 'Run tests';

    Test.prototype.run = function() {
      var port, server;
      this.singool.config.test = true;
      this.singool.config.init = false;
      this.singool.config.ignore = [];
      server = this.singool.createServer();
      port = process.env.PORT || 3000;
      server.listen(port);
      return console.log('Test server running at http://localhost:' + port);
    };

    return Test;

  })();

  module.exports = Test;

}).call(this);
