// Generated by CoffeeScript 1.6.1
(function() {
  var Clear,
    _this = this;

  Clear = (function() {

    function Clear(singool) {
      var _this = this;
      this.singool = singool;
      this.run = function() {
        return Clear.prototype.run.apply(_this, arguments);
      };
    }

    Clear.prototype.description = 'Delete build files';

    Clear.prototype.run = function() {
      return this.singool.clear();
    };

    return Clear;

  })();

  module.exports = Clear;

}).call(this);
