// Generated by CoffeeScript 1.6.1
(function() {
  var Server,
    _this = this;

  Server = (function() {

    function Server(singool) {
      var _this = this;
      this.singool = singool;
      this.run = function() {
        return Server.prototype.run.apply(_this, arguments);
      };
    }

    Server.prototype.description = 'Real time server';

    Server.prototype.serveStatic = false;

    Server.prototype.run = function() {
      var port, server;
      server = this.singool.createServer(this.serveStatic);
      port = process.env.PORT || 3000;
      server.listen(port);
      return console.log('Server running at http://localhost:' + port);
    };

    return Server;

  })();

  module.exports = Server;

}).call(this);
