// Generated by CoffeeScript 1.6.1
(function() {
  var TestServer,
    _this = this,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TestServer = (function(_super) {

    __extends(TestServer, _super);

    function TestServer(singool) {
      var _this = this;
      this.singool = singool;
      this.run = function() {
        return TestServer.prototype.run.apply(_this, arguments);
      };
    }

    TestServer.prototype.description = 'Run tests in the browser';

    TestServer.prototype.run = function() {
      return this.server();
    };

    return TestServer;

  })(require('./test'));

  module.exports = TestServer;

}).call(this);
