// Generated by CoffeeScript 1.6.1
(function() {
  var Coffee, cs, fs,
    _this = this;

  cs = require('coffee-script/lib/coffee-script/coffee-script');

  fs = require('fs');

  Coffee = (function() {

    function Coffee(singool) {
      var _this = this;
      this.singool = singool;
      this.run = function(module, filename) {
        return Coffee.prototype.run.apply(_this, arguments);
      };
    }

    Coffee.prototype.run = function(module, filename) {
      var source;
      source = fs.readFileSync(filename, 'utf8');
      return module._compile(cs.compile(source), filename);
    };

    return Coffee;

  })();

  module.exports = Coffee;

}).call(this);
