// Generated by CoffeeScript 1.6.1
(function() {
  var Singool,
    _this = this;

  Singool = (function() {

    function Singool(singool) {
      var _this = this;
      this.singool = singool;
      this.run = function(module, filename) {
        return Singool.prototype.run.apply(_this, arguments);
      };
    }

    Singool.prototype.run = function(module, filename) {
      var content, source;
      source = '';
      if (filename.indexOf('singool/config/index.singool' > -1)) {
        content = {
          theme: this.singool.config.theme,
          plugins: this.singool.config.plugins,
          test: this.singool.config.test
        };
        if (this.singool.config.test) {
          content.testCases = this.singool.testCases();
        }
        source = 'module.exports = ' + JSON.stringify(content) + ';';
      }
      return module._compile(source, filename);
    };

    return Singool;

  })();

  module.exports = Singool;

}).call(this);
