// Generated by CoffeeScript 1.6.1
(function() {
  var Underscore, fs, util,
    _this = this;

  fs = require('fs');

  util = require('util');

  Underscore = (function() {

    function Underscore(singool) {
      var _this = this;
      this.singool = singool;
      this.run = function(module, filename) {
        return Underscore.prototype.run.apply(_this, arguments);
      };
    }

    Underscore.prototype.run = function(module, filename) {
      var source;
      source = fs.readFileSync(filename, 'utf8');
      source = 'module.exports = _.template(' + util.inspect(source) + ');';
      return module._compile(source, filename);
    };

    return Underscore;

  })();

  module.exports = Underscore;

}).call(this);
